name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck -S error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck -S error
      - name: Run ShellCheck
        run: shellcheck -S error bin/* modules/*.sh lib/*.sh
